config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resource :home, only: [ :index ]
  
  resource :contact, only: [ :new, :create ], controller: 'contact'
  resource :about, only: [ :show ], controller: 'about' do
    put 'download'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  def headers
    {
      :subject => "My Contact Form",
      :to => "nhttien2609@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
  end

  def download
    resume_pdf ="#{Rails.root}/public/downloads/TienNguyen-resume.pdf"
    send_file(resume_pdf, :type => 'application/pdf/docx/html/htm/doc', :disposition => 'attachment')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    contact = Contact.create(contacts_params)
    if contact
      ContactMailer.notify_contact(contact).deliver_later
      redirect_to root_path
    end
  end

  private
    def contacts_params
      params.require(:contact).permit(:name, :email, :message)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def icon_for( name, type: :solid, **html_options )
    fa_class = []
    type = '' if type == :none
    fa_class << "fa#{type.to_s[0]}"
    fa_class << "fa-#{name.dasherize}"
    fa_class << "fa-2x"
    fa_class << html_options[:class] if html_options[:class]
    tag.i **html_options.merge(class: fa_class.join(' '))
  end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about/show.html.erb
<div class="page">
  <div class="row">
    <div class="col-sm">
      <h1 class="resume-title">tien nguyen</h1>
      <div class="row about-content">
        <div class="col-sm-7">
          <p class="title"><%= icon_for('file-download', :class => 'icon')%>Download the pdf version of my resume <%= link_to 'here', download_about_path, method: :put %>!</p>
          <h3 class="title"><%= icon_for('briefcase', :class => 'icon') %>Experience</h3>
          <div class="modified-card">
            <h5>Ruby on Rails developer trainee - fulltime | Kisko Labs Oy, Helsinki</h5>
            <p>Feb 2021 - now </p>
            <h5>Software developer intern - fulltime (remote) | Fairforce Oy, Helsinki</h5>
            <p>Jul 2020 - Nov 2020</p>
            <p>Develop the company web application with Ruby on Rails. Key responsibilities are: 
            <br>• Add new features, mostly on the back-end.
            <br>• Make tests (unit tests and system test).
            <br>• Tech-lead of the intern development team.</p>
          </div>

          <h3 class="title"><%= icon_for('laptop-code', :class => 'icon') %>Technical knowledge</h3>
          <div class="modified-card">
            <h5>Web frameworks</h5>
            <p>• Ruby on Rails
            <br>• React/ReactNative</p>
            <h5>Databases</h5>
            <p>• PostgreSQL
            <br>• MySQL
            <br>• Firebase</p>
            <h5>Networking</h5>
            <p>• Configure servers, routers, TCP/IP, LAN technology</p>
            <h5>Others</h5>
            <p>• Git
            <br>• Microsoft Office 365</p>
          </div>

          <h3 class="title"><%= icon_for('school', :class => 'icon') %>Education</h3>
          <div class="modified-card">
            <h5>South-Eastern Finland UAS | Bachelor of Engineering in Information Technology</h5>
            <p>Aug 2017 - Jul 2021
            <br>GPA: 4.41/5.00</p> 
          </div>

          <h3 class="title"><%= icon_for('language', :class => 'icon') %>Languages efficiencies</h3>
          <div class="modified-card">
          <p>• English: fluent
          <br>• Vietnamese: mothertongue
          <br>• Finnish: basic (I'm learning! Follow me on Duolingo: Tien475012 )</p>
          </div>
        </div>
        <%= image_tag "pngegg.png", :class => "col-sm d-none d-sm-block deco-img" %>
      </div>
    </div>
    
  </div>
</div>

app/views/contact/new.html.erb
<div class="page contact-content">
  <div class="row">
    <%= image_tag "source.gif", :class => "col-sm-4 d-none d-sm-block phone-photo" %>
    <div class="col-sm-7">
      <%= form_with model: @contact, url: contact_path, method: :post do |f| %>
        <h1 class="resume-title">contact me!</h1>
        <div>
          <%= f.label :name %>
          <%= f.text_field :name, class: 'field', :required => true %>
        </div>
        <div>
          <%= f.label :email %>
          <%= f.text_field :email, class: 'field', :required => true %>
        </div>
        <div>
          <%= f.label :message %>
          <%= f.text_area :message, class: 'textarea__long'%>
        </div>
        <p style="font-size: 12px">This will notify me by email. I'll reach back to you so please remember to leave me your email!</p>
        <%= f.submit "Save", class: "button" %>
      <% end %>
      <h5 style="margin-top: 30px">You can also reach me by social medias</h5>
      <%= link_to icon_for('linkedin-in', type: :brands), "https://www.linkedin.com/in/ttienism/", :target => "_blank", :class => "icon" %>
      <%= link_to icon_for('facebook', type: :brands), "https://facebook.com/ttienism", :target => "_blank", :class => "icon" %>
      <p style="margin-top: 30px">Thank you <3</p>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="page">
  <div class="row home-content">
    <div class="col-sm-4 d-none d-sm-block photo-content">
      <%= image_tag "me.jpg", :class => "home-photo img-responsive" %>
    </div>
    <div class="col-12 col-sm">
      <h1 class="resume-title">tien nguyen 🇻🇳</h1>
      <div class="row">
        <p class="col-sm"><%= icon_for('map-marker-alt') %> Espoo, Finland</p>
        <p class="col-sm"><%= icon_for('envelope')%> nhttien2609@gmail.com</p>
        <p class="col-sm"><%= icon_for('phone')%> +358 46 532 6894</p>
      </div>
      <div class="modified-card">
        <h3>currently, i am a thesis worker</h3>
        <br>
        <p>Hardworking, careful, responsible and committed are the top keywords I would use to describe myself. With a get-it-done attitude, I believe to better myself everyday at what I am doing and deliver results on-time. I learn as I go and I am always open to pick up new technology.</p>
        <br>
        <h5>Read more about me <%= link_to "here", about_path %>.</h5>
      </div>

      <div class="modified-card">
        <h3>Check me out!</h3>
        <%= link_to icon_for('github', type: :brands), "https://github.com/ttienism", :target => "_blank", :class => "icon" %>
        <%= link_to icon_for('linkedin-in', type: :brands), "https://www.linkedin.com/in/ttienism/", :target => "_blank", :class => "icon" %>
        <%= link_to icon_for('facebook', type: :brands), "https://facebook.com/ttienism", :target => "_blank", :class => "icon" %>
      </div>

    </div>
  </div>
</div>

app/views/layouts/_navigation_bar.html.erb
<div class="navbar navbar-expand-lg modified-navbar">
  <%= link_to 'Home', root_path, class: "navbar-item #{"active" if current_page?(root_path)}" %>
  <%= link_to 'About', about_path, class: "navbar-item #{"active" if current_page?(about_path)}" %>
  <%= link_to 'Contact', new_contact_path, class: "navbar-item navbar-item-last #{"active" if current_page?(contact_path)}" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tien's Porfolio</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload', defer: true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= favicon_pack_tag 'favicon/favicon-16x16.png' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navigation_bar' %>
    </header>
    <%= yield %>
  </body>
</html>